# Magic squares

In [1]:
import numpy as np

There is an algorithm for odd-sized squares, but I don't know the proof, and it doesn't work for even-sized squares:

* https://www.geeksforgeeks.org/magic-square/

In [26]:
N = 5

a = np.zeros((N,N))

i = N//2+1
j = N-2
for k in range(N**2):
    i = (i-1) % N
    j = (j+1) % N
    while a[i,j] != 0:
        i = (i-2) % N
        j = (j+1) % N
    a[i,j] = k+1


print(a)
print('Cols:',np.sum(a,axis=0))
print('Rows:',np.sum(a,axis=1))

[[ 6.  3. 25. 17. 14.]
 [ 2. 24. 16. 13. 10.]
 [23. 20. 12.  9.  1.]
 [19. 11.  8.  5. 22.]
 [15.  7.  4. 21. 18.]]
Cols: [65. 65. 65. 65. 65.]
Rows: [65. 65. 65. 65. 65.]
