# Numpy and matrix operations

In [1]:
import numpy as np

In [14]:
# Simple matrix operations
a = np.diag(np.arange(1,5))
b = np.ones((4,4))
c = np.matmul(a,b)
print(c)

[[1. 1. 1. 1.]
 [2. 2. 2. 2.]
 [3. 3. 3. 3.]
 [4. 4. 4. 4.]]


In [26]:
print(np.linalg.inv(a))

[[1.         0.         0.         0.        ]
 [0.         0.5        0.         0.        ]
 [0.         0.         0.33333333 0.        ]
 [0.         0.         0.         0.25      ]]


In [18]:
np.matmul(b,a)

array([[1., 2., 3., 4.],
       [1., 2., 3., 4.],
       [1., 2., 3., 4.],
       [1., 2., 3., 4.]])

In [27]:
np.outer(np.ones((4,1)),np.arange(1,5))

array([[1., 2., 3., 4.],
       [1., 2., 3., 4.],
       [1., 2., 3., 4.],
       [1., 2., 3., 4.]])

In [62]:
n = 1000
d = np.diag(np.arange(1,5)/4)
print(d)
X = np.random.normal(size=(n,4))
X = np.matmul(X,d)
C = np.matmul(X.transpose(),X)/n
print(np.round(C,2))

[[0.25 0.   0.   0.  ]
 [0.   0.5  0.   0.  ]
 [0.   0.   0.75 0.  ]
 [0.   0.   0.   1.  ]]
[[ 0.07  0.   -0.    0.01]
 [ 0.    0.24 -0.    0.01]
 [-0.   -0.    0.53 -0.01]
 [ 0.01  0.01 -0.01  0.96]]


In [24]:
np.random.randint(12)

0

In [12]:
a = np.random.randint(0,9,size=(3,3))
print(a)
a[3] # Unlike in Matlab, in Numpy it doesn't work.

[[8 5 0]
 [0 6 4]
 [8 3 5]]


IndexError: index 3 is out of bounds for axis 0 with size 3