# Numpy and matrix operations

Just trying different numpy methods, to see what will happen.

In [2]:
import numpy as np

In [9]:
# Gotcha: different array creators treat their arguments very differently: print(np.ones(3)) # Size

print(np.zeros(3)) # Size
print(np.eye(3)) # Rank
print(np.random.normal(3)) # Mean :(

[0. 0. 0.]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
2.571661828013993


In [9]:
print(np.ones((3,3))) # Shape
print(np.zeros((3,3))) # Shape
# print(np.eye((3,3))) # - returns an error
print(np.random.normal((3,3))) # - first argument is actually a vector of means

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[1.90564422 3.21976149]


In [32]:
print(np.random.normal(2,3)) # μ and σ
print(np.random.rand(2,3)) # Shape
# print(np.random.rand((2,3))) # - error

5.386580435975261
[[0.905439   0.86177986 0.25946369]
 [0.36944675 0.20413551 0.17417636]]


In [16]:
a = np.ones(shape=(2,2))
print(a)
print(a.shape)

b = np.random.normal(size=(2,2))
print(b)
print(b.shape) # This is obvious, but more of a "stairs into the camera" moment.

[[1. 1.]
 [1. 1.]]
(2, 2)
[[ 0.93341547 -0.15773932]
 [-0.86305114 -0.70624539]]
(2, 2)


In [21]:
print(np.full((2,3), 8))
print(np.ones((2,3))*8)
print(np.ones((2,3), dtype=int)*8)

[[8 8 8]
 [8 8 8]]
[[8. 8. 8.]
 [8. 8. 8.]]
[[8 8 8]
 [8 8 8]]


In [6]:
# np.full((2,3),[8,9]) # Error, doesn't broadcast

In [24]:
np.random.randint(10, size=(2,3))

array([[4, 8, 1],
       [6, 4, 8]])

In [8]:
a = np.array([3,2,5])
print(np.sort(a))   # Outputs sorted
print(a)            # But doesn't modify it
print(a.sort())     # Unlike this thing that modifies it and returns None
print(a)            # See, it's sorted now
print(a)
print(a.T) # Cannot 1D arrays flip to themselves (gotcha!)

[2 3 5]
[3 2 5]
None
[2 3 5]
[2 3 5]
[2 3 5]


In [11]:
a = np.array([[1,2,3],[4,5,6]])
print(a)
print(a.T)
print(a)
print(a.reshape(6))

[[1 2 3]
 [4 5 6]]
[[1 4]
 [2 5]
 [3 6]]
[[1 2 3]
 [4 5 6]]
[1 2 3 4 5 6]


In [36]:
# Gotcha: diff action of diff methods / properties
a = np.array([[8,4,2,1]])
print(a)
a.T
print(a)
a.reshape((2,-1))
print(a)
a.sort()
print(a)

[[8 4 2 1]]
[[8 4 2 1]]
[[8 4 2 1]]
[[1 2 4 8]]


In [12]:
# Appending

a = np.array([1,2,3])
print(a)
# a.append(5) # - Doesn't work, not an array method
np.append(a, 5)
print(a)
a = np.append(a,5)
print(a)
a = a.reshape(2,-1) # -1 is a wildcard!
print(a)
a = np.append(a,np.array([6,7])) # Doesn't produce an error, but linearizes the array
print(a)

[1 2 3]
[1 2 3]
[1 2 3 5]
[[1 2]
 [3 5]]
[1 2 3 5 6 7]


In [37]:
# Expanding Dimensions

a = np.array(1) # An array of a number is just a number
print(a)
print(np.expand_dims(a, axis=0))    # Expanding dimensions once makes it a 1D array
# print(np.expand_dims(a,axis=1))   # Error: cannot do axis1 without doing axis0 first
print(np.expand_dims(a, axis=(0,1)))# 2D

print(a[..., np.newaxis]) # Alternative notation for expanding

1
[1]
[[1]]
[1]


In [207]:
# Concatenation 

a = np.array([[1,2],[4,5]])
# print(np.concatenate( (a , np.array([0,0])) )) # Error: the 2nd array is 1D
print(np.concatenate( (a , np.array([[0,0]])) ))
print(np.concatenate( (a , np.array([[0,0]])), axis=0)) # Same as default behavior
print(np.concatenate( (a , np.array([[0,0]]).T), axis=1))
#print(np.concatenate( (a,a), axis=3)) # Error: Need to turn 2D arrays to 3D to make it happen

print(np.concatenate( (a[..., np.newaxis] , a[..., np.newaxis] ), axis=2)) # Works, but the result is confusing...

[[1 2]
 [4 5]
 [0 0]]
[[1 2]
 [4 5]
 [0 0]]
[[1 2 0]
 [4 5 0]]
[[[1 1]
  [2 2]]

 [[4 4]
  [5 5]]]


In [169]:
a = np.array([[1,2],[3,4]])
b = np.array([[6,7],[8,9]])
c = np.array([a,b])
print(c[0,:,:]) # The new dimension became 0, while old 0 and 1 moved to 1 and 2
print(c) # Which means that print() loops through axis 0, then slices on axes 1,2

[[1 2]
 [3 4]]
[[[1 2]
  [3 4]]

 [[6 7]
  [8 9]]]


In [178]:
a = np.array([[1,2],[3,4]])
c = np.expand_dims(a,2)
print(c)        # Gotcha: loops through 0, plots 1-2 as if they were 0-1
print(c[...,0]) # Welcome back to normal view

[[[1]
  [2]]

 [[3]
  [4]]]
[[1 2]
 [3 4]]


In [189]:
a = np.array([[1,2],[3,4]])
print(a[np.newaxis,...])
print(a[np.newaxis,:,:])
print(a[:,np.newaxis,:])
print(np.expand_dims(a, 1)) # Same as prev.

[[[1 2]
  [3 4]]]
[[[1 2]
  [3 4]]]
[[[1 2]]

 [[3 4]]]
[[[1 2]]

 [[3 4]]]


In [204]:
# Splitting

a = np.array(range(9))
print(a)
print(np.split(a,3))
# print(np.split(a,2)) # Error (because 2 doesn't divide 9)

a = np.array([[1,2,3], [4,5,6]])
print(a)
print(np.split(a,2))
print(np.split(a, 3, axis=1))

[0 1 2 3 4 5 6 7 8]
[array([0, 1, 2]), array([3, 4, 5]), array([6, 7, 8])]
[[1 2 3]
 [4 5 6]]
[array([[1, 2, 3]]), array([[4, 5, 6]])]
[array([[1],
       [4]]), array([[2],
       [5]]), array([[3],
       [6]])]


In [220]:
a = np.array([[1,2,3], [4,5,6]])
print(a)
print(np.split(a,2))
print(a[1:2, :])

[[1 2 3]
 [4 5 6]]
[array([[1, 2, 3]]), array([[4, 5, 6]])]
[[4 5 6]]


In [236]:
# Slicing 

a = np.array([[1,2,3], [4,5,6]])
print(a[1, :])
print(a[:, 2])
print(a[1, 2])
print(a[1:2, 2])
print(a[1, 2:3])
print(a[1:2, 2:3])

[4 5 6]
[3 6]
6
[6]
[6]
[[6]]


In [249]:
# Stacking and concatenating

a = np.array([[1,2]])
b = np.array([[3,4]])
print( np.concatenate((a,b)) )
print( np.vstack((a,b)) ) # Same thing
print( np.stack((a,b), axis=0) ) # Not the same thing! Extra dimension somehow!

[[1 2]
 [3 4]]
[[1 2]
 [3 4]]
[[[1 2]]

 [[3 4]]]


In [253]:
a = np.array([1,2])
b = np.array([3,4])
print( np.vstack((a,b)))
print( np.stack((a,b), axis=0)) # Same as above (creates a new axis)
print( np.stack((a,b), axis=1)) # Same as above (not sure why but ok)

print( np.hstack((a,b)))
print( np.concatenate((a,b), axis=0)) # Same as above (along an existing axis)

[[1 2]
 [3 4]]
[[1 2]
 [3 4]]
[[1 3]
 [2 4]]
[1 2 3 4]
[1 2 3 4]


In [48]:
# The summary of that gotcha above
# concat(axis=0) is equivalent to hstack for 1D arrays, bu vstack for 1×n arrays!

a = np.array([1,2])
b = a+2
assert np.array_equal(np.hstack((a,b)) , np.concatenate((a,b), axis=0))
print('concat axis=0 of 1D arrays:\n', np.concatenate((a,b), axis=0))

a = np.array([[1,2]])
b = a+2
assert np.array_equal(np.vstack((a,b)) , np.concatenate((a,b), axis=0))
print('concat axis=0 of 2D arrays:\n', np.concatenate((a,b), axis=0))

concat axis=0 of 1D arrays:
 [1 2 3 4]
concat axis=0 of 2D arrays:
 [[1 2]
 [3 4]]


In [260]:
a = np.array([[1,2],[3,4]])
b = a+4
print( np.vstack((a,b)))
print( np.concatenate((a,b), axis=0))
print( np.hstack((a,b)))
print( np.concatenate((a,b), axis=1))
print( np.stack((a,b), axis=0))

[[1 2]
 [3 4]
 [5 6]
 [7 8]]
[[1 2]
 [3 4]
 [5 6]
 [7 8]]
[[1 2 5 6]
 [3 4 7 8]]
[[1 2 5 6]
 [3 4 7 8]]
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [95]:
# Simple matrix operations
a = np.diag(np.arange(1,5))
b = np.ones((4,4))
c = np.matmul(a,b)
print(c)

[[1. 1. 1. 1.]
 [2. 2. 2. 2.]
 [3. 3. 3. 3.]
 [4. 4. 4. 4.]]


In [98]:
a @ b

array([[1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.]])

In [104]:
# a @ 1 # - Error. Scalar multipliation != matrix multiplication

In [7]:
print(np.ones(3))
print(np.zeros(3))
print(np.eye(3))
print(np.random.normal(3))

[1. 1. 1.]
[0. 0. 0.]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
2.8522744889738028


In [26]:
print(np.linalg.inv(a))

[[1.         0.         0.         0.        ]
 [0.         0.5        0.         0.        ]
 [0.         0.         0.33333333 0.        ]
 [0.         0.         0.         0.25      ]]


In [18]:
np.matmul(b,a)

array([[1., 2., 3., 4.],
       [1., 2., 3., 4.],
       [1., 2., 3., 4.],
       [1., 2., 3., 4.]])

In [27]:
np.outer(np.ones((4,1)),np.arange(1,5))

array([[1., 2., 3., 4.],
       [1., 2., 3., 4.],
       [1., 2., 3., 4.],
       [1., 2., 3., 4.]])

In [62]:
n = 1000
d = np.diag(np.arange(1,5)/4)
print(d)
X = np.random.normal(size=(n,4))
X = np.matmul(X,d)
C = np.matmul(X.transpose(),X)/n
print(np.round(C,2))

[[0.25 0.   0.   0.  ]
 [0.   0.5  0.   0.  ]
 [0.   0.   0.75 0.  ]
 [0.   0.   0.   1.  ]]
[[ 0.07  0.   -0.    0.01]
 [ 0.    0.24 -0.    0.01]
 [-0.   -0.    0.53 -0.01]
 [ 0.01  0.01 -0.01  0.96]]


In [24]:
np.random.randint(12)

0

In [62]:
a = np.array(range(9)).reshape((3,3))
print(a)
# a[3]          # Unlike in Matlab, in Numpy it doesn't work.
a.flatten()[3]  # This is how you do it

[[0 1 2]
 [3 4 5]
 [6 7 8]]


3

In [8]:
a = np.zeros(shape=(3,3,3))
a[...,1]

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [71]:
a = np.array(range(4))
print(a)
print(a+1)
print(a+a)
print(a*a)
print(a/a)
print(np.power(a,a)) # Power is also vectorized, huh :)

[0 1 2 3]
[1 2 3 4]
[0 2 4 6]
[0 1 4 9]
[nan  1.  1.  1.]
[ 1  1  4 27]


C:\Users\khakh\anaconda3\lib\site-packages\ipykernel_launcher.py:6: RuntimeWarning: invalid value encountered in true_divide
  
